### ISSUE TITLE
Latest release requires async_generator for Python 3.6

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/httpx-feedstock#38]
Hello, the dependency list needs to be updated to include `async_generator` for Python 3.6:
https://github.com/encode/httpx/blob/9b17671f155aa857fb52911d94357147ba2a3ea4/setup.py#L63

This means that the package can no longer be `noarch`.

Happy to make a PR if you're too busy. Let me know what you think.

Best wishes,
Richard

**Comment by PrimozGodec** [comment]
@hoechenberger thanks for the reminde. I do not know how I missed it. Would you mind checking the recipe changes? https://github.com/conda-forge/httpx-feedstock/pull/39
